import { ShoppingCart, Landmark, HeartPulse, Satellite, Bot, Plane, ShieldCheck, Link2, Car, ShoppingBag, Users, Cookie, Footprints, Building2, Layers, Dices, Gamepad2, Crown, Trophy, Joystick, LayoutTemplate, Gem, Sparkles, Wrench, Palette, Coins, type LucideIcon } from 'lucide-react';

export type Project = {
  id: number;
  title: string;
  category: string;
  description: string;
  technologies: string[];
  icon: LucideIcon;
  color: string;
  url?: string;
  image?: string;
  /** Figma prototype URL — when set, the detail page embeds it as a live,
   *  clickable prototype instead of (or alongside) the static screenshot. */
  figmaUrl?: string;
};

export const projects: Project[] = [
  {
    id: 1,
    title: 'E-Commerce Platform Testing',
    category: 'Quality Assurance',
    description: 'Comprehensive test automation and manual testing for a large-scale e-commerce platform, reducing production defects by 40%.',
    technologies: ['Selenium', 'JIRA', 'Postman', 'Jenkins'],
    icon: ShoppingCart,
    color: 'bg-blue-500',
  },
  {
    id: 2,
    title: 'Banking App Quality Assurance',
    category: 'Quality Assurance',
    description: 'Led security and performance testing for a mobile banking application, ensuring compliance with financial regulations.',
    technologies: ['JMeter', 'OWASP', 'JIRA', 'Appium'],
    icon: Landmark,
    color: 'bg-green-500',
  },
  {
    id: 3,
    title: 'Healthcare Portal Redesign',
    category: 'UI/UX Design',
    description: 'Designed an intuitive patient portal interface, improving user satisfaction scores by 60% through user research and prototyping.',
    technologies: ['Figma', 'Adobe Photoshop', 'Wireframing', 'User Research'],
    icon: HeartPulse,
    color: 'bg-purple-500',
  },
  {
    id: 4,
    title: 'Nationwide Satellite & Public Wi-Fi Connectivity',
    category: 'Network Engineering',
    description: 'Supported the planning, field deployment, and maintenance of DICT nationwide connectivity programs — including Low Earth Orbit satellite internet (PIALEOS) for underserved barangays, schools, and health facilities, plus public Wi-Fi rollouts (WITS, PICS-PP/PICS-MUN, PROVINET) across multiple regions.',
    technologies: ['LEO Satellite (VSAT)', 'Wireless Networking', 'Field Deployment', 'NOC Monitoring'],
    icon: Satellite,
    color: 'bg-orange-500',
  },
  {
    id: 5,
    title: 'QA Automation Framework',
    category: 'Quality Assurance',
    description: 'Built a scalable test automation framework using Selenium and Python, reducing testing time by 70%.',
    technologies: ['Python', 'Selenium', 'Pytest', 'CI/CD'],
    icon: Bot,
    color: 'bg-teal-500',
  },
  {
    id: 6,
    title: 'Travel App UI Design',
    category: 'UI/UX Design',
    description: 'Created a modern, user-friendly mobile app design for a travel booking platform with interactive prototypes.',
    technologies: ['Figma', 'Prototyping', 'UI Design', 'User Testing'],
    icon: Plane,
    color: 'bg-pink-500',
  },
  {
    id: 7,
    title: 'Philippine Navy VSAT & Endpoint Security Enhancement',
    category: 'Network Engineering',
    description: "Assisted in enhancing VSAT connectivity for the Philippine Navy's Maritime Situational Awareness System (MSAS) and supported the rollout of centrally managed endpoint security across Navy units.",
    technologies: ['VSAT', 'Sophos Endpoint Security', 'Defense/Government IT'],
    icon: ShieldCheck,
    color: 'bg-red-500',
  },
  {
    id: 8,
    title: 'API Testing Suite',
    category: 'Quality Assurance',
    description: 'Developed comprehensive API testing suites using Postman and automated regression tests for RESTful services.',
    technologies: ['Postman', 'REST API', 'Automation', 'Newman'],
    icon: Link2,
    color: 'bg-indigo-500',
  },
  {
    id: 9,
    title: 'VREDS – VR Driving School Trainer',
    category: 'Development',
    description: 'A Unity-based virtual reality driving simulator that lets instructors evaluate and train student drivers on road signs and driving etiquette in a standardized, immersive test environment.',
    technologies: ['Unity', 'C#', 'VR', 'Game Design'],
    icon: Car,
    color: 'bg-cyan-500',
    url: 'https://github.com/josux/vreds',
  },
  {
    id: 10,
    title: 'Food Delivery App UI Design',
    category: 'UI/UX Design',
    description: 'Designed the mobile UI for a food-delivery app as part of a national UI/UX design competition, reaching the finals. Covered end-to-end flows for browsing nearby shops and checkout, alongside related e-commerce, business, and SDG-aligned concept designs.',
    technologies: ['Figma', 'Mobile UI', 'Prototyping', 'E-Commerce'],
    icon: ShoppingBag,
    color: 'bg-amber-500',
    image: '/projects/food-delivery-app.png',
  },
  {
    id: 11,
    title: 'Big Brother Guild — Community Platform',
    category: 'UI/UX Design',
    description: 'Designed the brand identity and landing page for Big Brother Guild, a Discord-based community built around NFT games that support fostering, assistance, and stability initiatives.',
    technologies: ['Figma', 'Brand Identity', 'Landing Page Design', 'Community Platforms'],
    icon: Users,
    color: 'bg-rose-500',
    image: '/projects/big-brother-guild.png',
  },
  {
    id: 12,
    title: 'Hokkaido Baked Cheese Tart — Website Design',
    category: 'UI/UX Design',
    description: 'Designed a warm, appetite-driving landing page for a baked-cheese-tart bakery, pairing full-bleed product photography with a simple ordering call-to-action.',
    technologies: ['Figma', 'Web Design', 'Prototyping'],
    icon: Cookie,
    color: 'bg-yellow-500',
    image: '/projects/hokkaido-cheese-tart.jpg',
    figmaUrl: 'https://www.figma.com/proto/VZTvlfsRH4ndmA4vKPaJ2r/Hokkaido-Baked-Cheese-Tart?node-id=18-129&starting-point-node-id=18%3A129',
  },
  {
    id: 13,
    title: 'Nike Shoes — Product Landing Page',
    category: 'UI/UX Design',
    description: 'Concept redesign of a Nike product page with a dark, cyberpunk aesthetic — built to spotlight a single hero shoe with bold typography and feature callouts.',
    technologies: ['Figma', 'Product Page', 'Prototyping'],
    icon: Footprints,
    color: 'bg-slate-700',
    image: '/projects/nike-shoes.jpg',
    figmaUrl: 'https://www.figma.com/proto/ZJIvs7g1YMqnVFehN9y5Iq/Nike-Shoes?node-id=50-2&p=f&t=OcstokQjxb3aXbUw-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=50%3A2',
  },
  {
    id: 14,
    title: 'Makati City — Government Portal Concept',
    category: 'UI/UX Design',
    description: 'Designed a citizen-facing local government portal concept for Makati City, organizing online services, events, and COVID-19 information behind a clear tabbed layout.',
    technologies: ['Figma', 'Civic UX', 'Information Architecture'],
    icon: Building2,
    color: 'bg-blue-600',
    image: '/projects/makati-city.jpg',
    figmaUrl: 'https://www.figma.com/proto/UUOWTt2WXca8aIXtc694rm/Makati-City?node-id=12-72&p=f&t=oehnY2hiaMR561HR-0&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=12%3A72',
  },
  {
    id: 15,
    title: 'Limbaga 77',
    category: 'UI/UX Design',
    description: 'Interactive prototype exploring layout and interaction patterns for the Limbaga 77 concept, built and tested end-to-end in Figma.',
    technologies: ['Figma', 'Prototyping', 'Interaction Design'],
    icon: Layers,
    color: 'bg-violet-500',
    image: '/projects/limbaga-77.jpg',
    figmaUrl: 'https://www.figma.com/proto/EjjOp0VxdQVAdGLsJsz9hp/Limbaga-77?node-id=1-227&p=f&t=d24Q9hpQNRrh9oCB-0&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A227',
  },
  {
    id: 16,
    title: 'ZEN Casino — iGaming UI',
    category: 'UI/UX Design',
    description: 'Designed a full iGaming platform UI concept — lobby, promotions, and sign-up flow — as part of a series exploring high-conversion casino/entertainment interfaces.',
    technologies: ['Figma', 'iGaming UI', 'Prototyping'],
    icon: Dices,
    color: 'bg-emerald-600',
    image: '/projects/zen-casino.jpg',
    figmaUrl: 'https://www.figma.com/proto/QLLuqslYQqtRR4XaD8URq8/ZEN-Casino?node-id=26-207&p=f&t=MlcMRtafF4LZm7uK-0&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=26%3A207',
  },
  {
    id: 17,
    title: 'Hero Slots — Themed Slots Platform UI',
    category: 'UI/UX Design',
    description: 'Designed a superhero-themed online slots platform UI, combining bold character art with a clear registration and bonus-offer flow.',
    technologies: ['Figma', 'iGaming UI', 'Visual Design'],
    icon: Gamepad2,
    color: 'bg-red-600',
    image: '/projects/hero-slots.jpg',
    figmaUrl: 'https://www.figma.com/proto/XNFH091KtHnEBFDAWI2yjP/Hero-Slots?node-id=1-4&p=f&t=hDMTie4xDV0eL9xa-0&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A4',
  },
  {
    id: 18,
    title: 'King Casino — iGaming UI',
    category: 'UI/UX Design',
    description: 'Designed a jungle/adventure-themed casino platform UI concept, focused on a strong welcome-bonus hero section and clear primary navigation.',
    technologies: ['Figma', 'iGaming UI', 'Prototyping'],
    icon: Crown,
    color: 'bg-yellow-600',
    image: '/projects/king-casino.jpg',
    figmaUrl: 'https://www.figma.com/proto/T5I4qFrx8mfL1YopFhEu0v/King-Casino?node-id=12-1147&p=f&t=Y1JP1k7iqHfVSJ96-0&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=12%3A1147',
  },
  {
    id: 19,
    title: 'Casino Legends — iGaming UI',
    category: 'UI/UX Design',
    description: 'Designed a premium-feeling casino platform concept, part of an ongoing exploration of visual identity and layout patterns across iGaming brands.',
    technologies: ['Figma', 'iGaming UI', 'Branding'],
    icon: Trophy,
    color: 'bg-amber-600',
    image: '/projects/casino-legends.jpg',
    figmaUrl: 'https://www.figma.com/proto/ZfqYUDy3Ko1CusunPb0kbp/Casino-Legends?node-id=14-2260&p=f&t=UDMG7RBIqKoLcJES-0&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=14%3A2260',
  },
  {
    id: 20,
    title: 'Arcade Casino — iGaming UI',
    category: 'UI/UX Design',
    description: 'Designed a bold, retro pixel-art branded casino landing page, built around a playful arcade-game visual identity and a clear bonus call-to-action.',
    technologies: ['Figma', 'iGaming UI', 'Prototyping'],
    icon: Joystick,
    color: 'bg-fuchsia-600',
    image: '/projects/arcade-casino.jpg',
    figmaUrl: 'https://www.figma.com/proto/ROR0ACjtVbwve3quRr9oWQ/Arcade-Casino?node-id=77-140&starting-point-node-id=77%3A140',
  },
  {
    id: 21,
    title: 'UX Design Landing Page — Casino Onboarding',
    category: 'UI/UX Design',
    description: 'Designed a clean online casino landing page as a UX case study, focused on a simple onboarding flow and first-top-up bonus offer.',
    technologies: ['Figma', 'UX Design', 'Prototyping'],
    icon: LayoutTemplate,
    color: 'bg-sky-600',
    image: '/projects/ux-design-landing.jpg',
    figmaUrl: 'https://www.figma.com/proto/FeqVPvwY8f3RwS6v1tJVN8/UX-Design-Landing-page?node-id=24-386&starting-point-node-id=24%3A386',
  },
  {
    id: 22,
    title: "Templar's Gold — iGaming Brand Concept",
    category: 'UI/UX Design',
    description: 'Designed a treasure-hunt-themed crypto casino brand concept, pairing a distinct visual identity with a bonus-driven landing page layout.',
    technologies: ['Figma', 'iGaming UI', 'Branding'],
    icon: Gem,
    color: 'bg-orange-600',
    image: '/projects/templars-gold.jpg',
    figmaUrl: 'https://www.figma.com/proto/Qnq3vVG2biJCrnDZYR1Oln/Templar-s-Gold?node-id=8-106&p=f&t=Ew4rHfI8VIFnD4uu-0&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=8%3A106',
  },
  {
    id: 23,
    title: 'Casino Origin — iGaming UI',
    category: 'UI/UX Design',
    description: 'Designed a sleek, ocean-themed online casino UI concept with a rotating promotions carousel and prominent primary call-to-action.',
    technologies: ['Figma', 'iGaming UI', 'Prototyping'],
    icon: Sparkles,
    color: 'bg-indigo-600',
    image: '/projects/casino-origin.jpg',
    figmaUrl: 'https://www.figma.com/proto/988s5zAOB1mG21h4n8n9Uy/CASINO-ORIGIN?node-id=68-430&starting-point-node-id=68%3A430',
  },
  {
    id: 24,
    title: 'Hardware Website Collaboration',
    category: 'UI/UX Design',
    description: 'Collaborated on the UI design for an automotive-care e-commerce website, working alongside another designer on the shopping cart, product listings, and page structure.',
    technologies: ['Figma', 'Collaboration', 'E-Commerce'],
    icon: Wrench,
    color: 'bg-stone-600',
    image: '/projects/hardware-website.jpg',
    figmaUrl: 'https://www.figma.com/proto/N936gPfp9gsxLUktmeAO1e/Hardware-Website-Collaboration--1?node-id=121-2134&starting-point-node-id=121%3A2134',
  },
  {
    id: 25,
    title: 'Free UI Design — Account Login Practice Project',
    category: 'UI/UX Design',
    description: 'A self-directed practice project redesigning an account login/registration flow for a business web portal, focused on clear form hierarchy and account-type selection.',
    technologies: ['Figma', 'UX Design', 'Self-Directed Practice'],
    icon: Palette,
    color: 'bg-lime-600',
    image: '/projects/free-ui-design-project.jpg',
    figmaUrl: 'https://www.figma.com/proto/Gz40oZw87yFGZgwkIcqeB1/Free-UI-Design--For-Project-?node-id=5-144&starting-point-node-id=5%3A144',
  },
  {
    id: 26,
    title: 'Aesthetic Casino — Lottery & Casino UI',
    category: 'UI/UX Design',
    description: 'Designed a bright, playful online lottery and casino UI concept, pairing a bold registration panel with vibrant, high-contrast visuals.',
    technologies: ['Figma', 'iGaming UI', 'Visual Design'],
    icon: Coins,
    color: 'bg-pink-600',
    image: '/projects/aesthetic-casino.jpg',
    figmaUrl: 'https://www.figma.com/proto/E1T4erLS0pkZsf5jWDcwO6/Aesthetic-Casino?node-id=15-134&p=f&t=ckDhAgCD4byjfAHK-0&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=15%3A134',
  },
];

export const categories = ['All', 'Quality Assurance', 'UI/UX Design', 'Network Engineering', 'Development'];

export function getProjectById(id: number): Project | undefined {
  return projects.find((project) => project.id === id);
}
